### ISSUE TITLE
Improve conda recipe

### ISSUE THREAD

**Issue by loic-couderc** [bonsai-team/matam#18]
For now (see #5) , the process of building a conda package uses the default build.py script. It will be preferable to write a specific build script:
Instead of using submodules, use conda requirements.

To enable this, the code have to be slightly modified to search binaries from matam dir first then from the path.

**Comment by loic-couderc** [comment]
I wrote a conda recipe which do not compile the dependencies but instead uses conda requirements.
It works perfectly well, except for SGA on centos 6 (glibc error).
I think it will be preferable to wait for the support of a new gcc compiler (i.e. gcc >= 4.9.0) before carry on.

**Comment by ppericard** [comment]
This issue is too generic. Closing it for now
