### ISSUE TITLE
Docker classification issue:

### ISSUE THREAD

**Issue by EisenRa** [bonsai-team/matam#20]
Dear authors,

Thank you for making this great software!

I'm having an issue running MATAM through docker, it works fine until the classification step, then outputs this error:

INFO - Write abundance informations to: /matam/matam_assembly/scaffolds.NR.min_500bp.fa.abd
INFO - === Taxonomic assignment ===
No valid binary found for classifier

Seems like it's not finding the rdp binaries?

Any help would be greatly appreciated.

Best regards,
Raphael

**Comment by ppericard** [comment]
Yes, you're right, we didn't update the Dockerfile with the last build. We'll correct that asap.
By curiosity, since you're the first user to use MATAM through docker, what guided your choice of distribution mode ? We tend to encourage our user to get MATAM with conda since it is easier to install and use, but it doesn't run on all operating systems.

**Comment by ppericard** [comment]
@loic-couderc : we need to check the dependencies installed on the ubuntu image. We need to add at least ant.

**Comment by loic-couderc** [comment]
Dear @EisenRa,

I have updated the docker image to take into account your issue.
You can download the new image:
```bash
docker pull bonsaiteam/matam
```
Then, to avoid to run all MATAM's steps again, you can add the flag `--resume_from abundance_calculation` to your command line with the same parameters.

**Comment by EisenRa** [comment]
Dear Pierre,

Thank you for the quick response!

I've just tried installing it and running it through conda on our linux server -- works fine!

The reason that I started with docker was that my work machine is a Mac, and I've historically had issues installing dependencies etc. on the server due to permissions. Though it appears that conda worked fine!

Much appreciated,
Raphael
