### ISSUE TITLE
Duplicate the STDOUT and STDERR outputs in a log file

### ISSUE THREAD

**Issue by ppericard** [bonsai-team/matam#26]
We should have a log file to store everything that currently output to STDOUT and STDERR.

Currently, if people dont redirect their STDOUT and STDERR in a file, they can lose important informations about the run.

The implementation should be fexible enough so that it is easy to chose whever we want to output to the terminal or to the log file, or both.

**Comment by loic-couderc** [comment]
Is the "both" choice relevant?
* logging to a file: then use `tail -f <logfile>` to see the ouput in the terminal.
* logging to terminal: then use `tee` to duplicate the output:
```bash
matam_assembly.py ... | tee <logfile>
```

Only the second case could be problematic in the way that you have to know what you want when you run the command.

**Comment by loic-couderc** [comment]
I propose to clarify the verbosity policy of MATAM as follows:
- default: log all messages with an INFO level or above. (currently not the case: WARNING or above)
- verbose: 
    - increase the verbosity of the tools used by MATAM (mainly first level tools)
    - log stdout/stderr of this tools
    - show final stats
- debug: 
    - verbose mode + log all messages with DEBUG level or above (typically, command lines etc...).
    - use a logger formatter with more info (time, module...)
