### ISSUE TITLE
preferred installation method

### ISSUE THREAD

**Issue by rchikhi** [bonsai-team/matam#27]
I recall Pierre saying that Conda was the preferred method for getting MATAM, yet the README appears to recommend doing source compilation.

Also these "sudo apt-get" for a "quick installation" aren't user friendly, not so many users are root on their machine.

**Comment by loic-couderc** [comment]
From https://github.com/bonsai-team/matam#getting-started:

> The recommended way of getting MATAM is through conda (see below)

In all cases, we have to rethink the README. The amount of info can be confusing.

**Comment by ycl6** [comment]
The "Source code (zip/tar.gz)" provided in the releases page lacks the submodule contents, so does using `git clone https://github.com/bonsai-team/matam.git`

To download the complete source code (including submodules) for compilation, use
`git clone --recursive https://github.com/bonsai-team/matam.git`

**Comment by ppericard** [comment]
> The "Source code (zip/tar.gz)" provided in the releases page lacks the submodule contents

Yes, this is a feature lacking in GitHub. This is why we are not recommending getting MATAM source code this way.

> so does using `git clone https://github.com/bonsai-team/matam.git`

In fact, this is not a problem. If you do not use the `--recursive` option when cloning the repository, the submodules will be recovered by running the `build.py` script to compile MATAM.
