### ISSUE TITLE
Rethink the README

### ISSUE THREAD

**Issue by loic-couderc** [bonsai-team/matam#28]
From time to time, the README became bigger and bigger and the amount of information displayed can be overwhelming or unclear (#27).

We have to re-organized the README

**Comment by ppericard** [comment]
I think the README should only have the basic information on how to get MATAM, install it and run it by default.
Details about the program parameters, the method, and any other information should be organized and accessible through another way. What about using the Github Wiki ? Like here for example: https://github.com/jts/sga/wiki

**Comment by ghost** [comment]
In my opinion, the README file should have an intuitive order. It should start with installation and installation test. Once installation is fully covered, the README should give further information on "how to run", and that includes dabatases, input and output. Further informatin can be displayed with a -h flag when running the tool.
