### ISSUE TITLE
Standardize RDP taxa

### ISSUE THREAD

**Issue by ppericard** [bonsai-team/matam#39]
Some RDP assignments can have additional levels like subclass or suborder. This badly translates into the Krona file where taxa level do not have the same depth. Ex genus will be at level 6 for most assignment, but can be at level 8 for those particular assignments, while the suborder will be at level 6.

A simple way to correct the problem would be to generate a krona file only with a fixed number of level, which means extracting from the RDP assignments only the 6 standard levels.

**Comment by loic-couderc** [comment]
Using rdp classifier with the option `-f fixrank` instead of `-f allrank` should do the trick:
