### ISSUE TITLE
anaconda salford_systems channel does not exist anymore

### ISSUE THREAD

**Issue by loic-couderc** [bonsai-team/matam#60]
The installation through conda is broken.

**Comment by loic-couderc** [comment]
Try to replace the salford_systems channel by psi4 (gcc-5) & ostrokach (libgcc-5)
```bash
conda config --add channels psi4
conda config --add channels ostrokach
```

Finally, I have uploaded the salford_systems package from my local computer to our anaconda repository as this packages are really sensitive for us.

**Comment by ppericard** [comment]
Could it be because gcc5 is going to be integrated in the main conda repository ?

**Comment by loic-couderc** [comment]
@ppericard Maybe but there is no news in that way.
