### ISSUE TITLE
install matam on HPC without sudo permissions

### ISSUE THREAD

**Issue by quetjaune** [bonsai-team/matam#64]
First, thank you for MATAM, i find it very useful.

I was trying to install it through conda in HPC but when running matam_assembly.py, get "No valid binary found for classifier". I could not find what is the issue here. Conda is the best option to install in HPC?
Any suggestion are welcome

**Comment by loic-couderc** [comment]
Hi @quetjaune,

Conda is the recommended way of installing MATAM, even on HPC infrastructure.

From your error message, i can say that the classifier binary is not in your PATH.
This binary come along with the installation of RDP -- rdptools conda package.

Maybe an error occurred during the installation.
Are you sure that the installation process ended well?

An option would be to re-install this package:
```bash
conda install -c bioconda rdptools
```
Then, to check the installation, run the following command in your terminal: `classifier`
If all went well, something like this will be printed out:
> USAGE: ClassifierMain <subcommand> <subcommand args ...>
default command is classify
>	classify      - classify one or multiple samples
>	crossvalidate - cross validate accuracy testing
> ....
