### ISSUE TITLE
Be less stringent when filtering RDP results

### ISSUE THREAD

**Issue by loic-couderc** [bonsai-team/matam#67]
Currently, in MATAM_V1.5.2, the following filter is applied on RDP results:
when the RDP confidence threshold (at genus level) is under a threshold of 0.8, then tag all taxonomic nodes as "unclassified".

Exemple:
```
# before
3015            Bacteria        domain  1.0     "Proteobacteria"        phylum  1.0     Alphaproteobacteria     class   1.0     Rhodospirillales        order   0.9     Rhodospirillaceae       family  0.62    Rhodovibrio     genus   0.27

# after
3015    unclassified    domain  1.0     unclassified    phylum  1.0     unclassified    class   1.0     unclassified    order   0.9     unclassified    family  0.62    unclassified    genus   0.27
```

But doing this is a potential loss of informations.
It will make more sense to replace only the taxonomic levels under the given threshold.

Exemple:
```
# before
3015            Bacteria        domain  1.0     "Proteobacteria"        phylum  1.0     Alphaproteobacteria     class   1.0     Rhodospirillales        order   0.9     Rhodospirillaceae       family  0.62    Rhodovibrio     genus   0.27

# after
3015    Bacteria        domain  1.0     Proteobacteria  phylum  1.0     Alphaproteobacteria     class   1.0     Rhodospirillales        order   0.9     unclassified    family  0.62    unclassified    genus   0.27
```

**Comment by PavlaDe** [comment]
Hello, 

I ran MATAM on my metagenomes usind the -v --perform_taxonomic_assignment. And it ran without error but when I looked at the krona plots with 70% unclassified which is due to the genus problematic. 

How do I implement the adjusted enhancement to rdp.py in order to get the updated and more accurate krona files? 
I do not want to rerun the assembly steps as these seem to be fine. 

Thanks, 

Pavla

**Comment by loic-couderc** [comment]
Hi @PavlaDe,

At the moment, the new filtering method is available in develop branch.
I will release a new version of MATAM with this modification in the next days.
Then you will be able to re-run from the "abundance_calculation" step of MATAM with:
` -v --perform_taxonomic_assignment --resume_from abundance_calculation`

**Comment by loic-couderc** [comment]
The new MATAM v1.5.3 is now available as a conda package.
