### ISSUE TITLE
Last version 1.5.3 on Conda

### ISSUE THREAD

**Issue by lecorguille** [bonsai-team/matam#69]
Hi here,

Your badge said 1.5.3 but it seems that it only target the 1.5.2.
Some people requested us to install the very last version. 
It seems that your tool is useful, congrats! :)

**Comment by loic-couderc** [comment]
Hi @lecorguille,

I'm currently realising the v1.5.3 of MATAM. The generation of the conda package is not automated for now.
It will be available soon.

**Comment by loic-couderc** [comment]
The new MATAM v1.5.3 is now available as a conda package.
