### ISSUE TITLE
CRITICAL - unrecognized arguments: --cup

### ISSUE THREAD

**Issue by fanhuan** [bonsai-team/matam#72]
Dear all,

I don't seem to be able to use multiple cores. When I try to set the number of CUPs by:

$  matam_assembly.py --cup 10 -i test.fq

It complains:
`CRITICAL - unrecognized arguments: --cup 10`

I am on Ubuntu 16.04 with 16 cores. 

Thanks ahead.

**Comment by loic-couderc** [comment]
Hi @fanhuan,

you have made a typo. The option is not `--cup` but `--cpu`.

**Comment by fanhuan** [comment]
This is embarrassing. I did make a typo there in the previous thread but I did have a problem previously when trying to use --cpu, however not able to reproduce it anymore, which is good. Sorry for the disturbance.

**Comment by loic-couderc** [comment]
No problem. Do not hesitate to reopen if you can reproduce the issue.
