### ISSUE TITLE
site hosting the matam standard DB can't be reached

### ISSUE THREAD

**Issue by slambrechts** [bonsai-team/matam#74]
Hi there,

When trying `index_default_ssu_rrna_db.py -d $DBDIR --max_memory 10000`, I get:

```
--2019-05-06 16:29:52--  http://bioinfo.lifl.fr/matam/SILVA_128_SSURef_NR95.tar.bz2
Resolving bioinfo.lifl.fr... 193.48.186.124
Connecting to bioinfo.lifl.fr|193.48.186.124|:80... failed: Connection timed out.
```

It keeps retrying, but fails every time

Also manually trying to download http://bioinfo.lifl.fr/matam/SILVA_128_SSURef_NR95.tar.bz2 does not seem to work

Am I the only one experiencing this problem or not?

Cheers,

Sam

**Comment by ppericard** [comment]
Hi @SamLambrechtsUGent,

Our servers hosting those files are currently undergoing major maintenance. They should be back online in a few days.

Cheers,

Pierre

**Comment by slambrechts** [comment]
Hi Pierre,

Thank you for your answer. You don't happen to have a local copy of the standard matam database tar file you're able to share? e.g. one that is hosted on another server perhaps? Apologies for the impatience :)

Cheers,

Sam

**Comment by loic-couderc** [comment]
Hi @SamLambrechtsUGent,

The servers are back online !
Sorry for the inconvenience caused by the maintenance.
