### ISSUE TITLE
Matam assembly error

### ISSUE THREAD

**Issue by mkarlik93** [bonsai-team/matam#77]
Dear all,

I am trying to assemble merged ilumina reads, I got this error:

header = line[1:].split()[0]
IndexError: list index out of range

**Comment by loic-couderc** [comment]
Hi @mkarlik93,

Could you please join the full error message.

From this error message, I guess the error is coming from the function reading the FASTQ file.
Have you any sequences without SEQID in your FASTQ ? (only '@' will be present on the header)
You can use the following command line to check.
(Be aware than if you are unlucky, the '@' can come from the quality lines)
```bash
grep -c '^@$' PATH_TO_YOUR_FASTQ

```

**Comment by mkarlik93** [comment]
Hi @loic-couderc,

Thanks for quick reply,

but what if I have reads only in fasta format? Is there any way to specify format of the input ?

**Comment by loic-couderc** [comment]
MATAM is normally able to handle reads in FASTA or FASTQ format.
If you want more helps, please, join the full error message. It will be hard to determine what's wrong otherwise.

**Comment by ppericard** [comment]
No answer for 2 months. Closing this temporarily
