### ISSUE TITLE
Missing classifier should not prevent matam_assembly.py from running

### ISSUE THREAD

**Issue by ppericard** [bonsai-team/matam#84]
Since the RDP classifier is optional for MATAM, and only useful for rRNA assembly, missing the classifier binary should not prevent the rest of the pipeline of running. But it should definitely be a warning.

This is even more important since compiling the RDP classifier can often fail because the server hosting the training dataset is down. We then should be able to run MATAM up to the final assembly and restart another run later to perform classification.

**Comment by loic-couderc** [comment]
The classifier is optional but if the `--perform_taxonomic_assignment` is used, then it is mandatory.
Based on this flag, we can prevent or not the execution of MATAM.

**Comment by ppericard** [comment]
Maybe also add a note to the error message saying that MATAM can still be run by removing the `--perform_taxonomic_assignment` flag
