### ISSUE TITLE
Input read fastq

### ISSUE THREAD

**Issue by rprops** [bonsai-team/matam#99]
In the guidelines a single fastq is shown as input for ´matam´. In the case of both forward and reverse read datasets (i.e. paired end read data) - how should these be fed to the algorithm? Interleaved? just merged?

Thx!

**Comment by loic-couderc** [comment]
Hi @rprops,

The reads can be interleaved or just merged. But, for now, MATAM will treat them as single reads.

**Comment by rprops** [comment]
understood - thx!
